# Generated by Django 5.1.7 on 2025-04-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Должность"
            ),
        ),
    ]
