# Generated by Django 5.1.7 on 2025-05-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_approval_date_user_approved_user_patronymic_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="approval_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="approved",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Организация"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Регион"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужской"), ("F", "Женский")],
                max_length=1,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Админ"),
                    ("curator", "Куратор"),
                    ("moderator", "Модератор"),
                    ("specialist", "Специалист"),
                    ("volunteer", "Волонтер"),
                    ("blocked", "Заблокированный"),
                ],
                default="specialist",
                max_length=20,
            ),
        ),
    ]
