# Generated by Django 5.1.7 on 2025-05-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_options_remove_user_approval_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approval_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата одобрения"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Одобрен"),
        ),
    ]
