# Generated by Django 5.1.7 on 2025-05-16 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("written_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "В ожидании"),
                            ("review", "На проверке"),
                            ("accepted", "Принято"),
                            ("rejected", "Отказано"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chapters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_chapters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="edited_chapters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Главы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ChapterRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="content.chapter",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chapter_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter Revision",
                "verbose_name_plural": "Chapter Revisions",
                "ordering": ["-edited_at"],
            },
        ),
        migrations.CreateModel(
            name="QA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                ("answer", models.TextField(max_length=3000)),
                ("written_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "В ожидании"),
                            ("review", "На проверке"),
                            ("accepted", "Принято"),
                            ("rejected", "Отказано"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("max_links", models.PositiveSmallIntegerField(default=3)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_qas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="edited_qas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QAReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="content.qa",
                    ),
                ),
            ],
            options={
                "verbose_name": "QA Reference",
                "verbose_name_plural": "QA References",
            },
        ),
        migrations.CreateModel(
            name="QARevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                ("answer", models.TextField(max_length=3000)),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qa_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="content.qa",
                    ),
                ),
            ],
            options={
                "verbose_name": "QA Revision",
                "verbose_name_plural": "QA Revisions",
                "ordering": ["-edited_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("written_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "В ожидании"),
                            ("review", "На проверке"),
                            ("accepted", "Принято"),
                            ("rejected", "Отказано"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="content.chapter",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="edited_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Разделы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="section_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="content.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section Revision",
                "verbose_name_plural": "Section Revisions",
                "ordering": ["-edited_at"],
            },
        ),
        migrations.CreateModel(
            name="Subsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("written_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "В ожидании"),
                            ("review", "На проверке"),
                            ("accepted", "Принято"),
                            ("rejected", "Отказано"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subsections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_subsections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="edited_subsections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="content.section",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Подразделы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SubsectionRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subsection_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subsection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="content.subsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subsection Revision",
                "verbose_name_plural": "Subsection Revisions",
                "ordering": ["-edited_at"],
            },
        ),
        migrations.CreateModel(
            name="QA_Subsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("copy_number", models.PositiveSmallIntegerField()),
                (
                    "qa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_subsections",
                        to="content.qa",
                    ),
                ),
                (
                    "subsection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_subsections",
                        to="content.subsection",
                    ),
                ),
            ],
            options={
                "unique_together": {("qa", "subsection", "copy_number")},
            },
        ),
    ]
