# Generated by Django 5.1.7 on 2025-05-16 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingStatusLevels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_name", models.CharField(max_length=20, unique=True)),
                ("min_hours", models.PositiveIntegerField()),
                ("max_hours", models.PositiveIntegerField()),
                ("color_code", models.CharField(max_length=7)),
            ],
            options={
                "verbose_name": "Уровень ожидания",
                "verbose_name_plural": "Уровни ожидания",
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Создание"),
                            ("update", "Обновление"),
                            ("delete", "Удаление"),
                            ("review", "Проверка"),
                            ("login", "Вход"),
                            ("logout", "Выход"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_details", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог",
                "verbose_name_plural": "Логи",
            },
        ),
        migrations.CreateModel(
            name="MaterialReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("chapter", "Chapter"),
                            ("section", "Section"),
                            ("subsection", "Subsection"),
                            ("qa", "QA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("material_id", models.PositiveIntegerField()),
                ("written_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("accepted", "Принято"),
                            ("accepted_with_changes", "Принято с изменениями"),
                            ("rejected", "Отклонено"),
                        ],
                        max_length=30,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("edited_content", models.JSONField(blank=True, null=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Проверка материала",
                "verbose_name_plural": "Проверки материалов",
            },
        ),
        migrations.CreateModel(
            name="RevisionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("chapter", "Chapter"),
                            ("section", "Section"),
                            ("subsection", "Subsection"),
                            ("qa", "QA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("material_id", models.PositiveIntegerField()),
                ("written_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("changes", models.JSONField()),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revision_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "История изменений",
                "verbose_name_plural": "Истории изменений",
            },
        ),
    ]
