# Generated by Django 5.1.7 on 2025-05-17 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_pendingstatuslevels_log_materialreview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="written_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="qa",
            name="written_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="section",
            name="written_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="written_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
